name: HOFOR Scraper
version: '0.1.0'
slug: hofor_scraper
description: Scrapes HOFOR consumption data and publishes to InfluxDB
url: https://github.com/Jensen95/homeassistant-hofos
arch:
  - amd64
startup: application
boot: auto
init: false
map:
  - share:rw
options:
  hofor_kundenummer: ''
  hofor_bs_kundenummer: ''
  influxdb_url: 'http://a0d7b954-influxdb:8086'
  influxdb_token: ''
  influxdb_org: 'homeassistant'
  influxdb_bucket: 'homeassistant/autogen'
  water_price_per_m3: 0
  water_price_currency: 'DKK'
  scrape_interval_hours: 3
  enable_backfill: true
  backfill_days: 365
  log_level: 'info'
schema:
  hofor_kundenummer: str
  hofor_bs_kundenummer: password
  influxdb_url: str
  influxdb_token: password
  influxdb_org: str
  influxdb_bucket: str
  water_price_per_m3: float?
  water_price_currency: str?
  scrape_interval_hours: int(1,24)
  enable_backfill: bool?
  backfill_days: int(1,730)?
  log_level: list(debug|info|warn|error)
image: ghcr.io/jensen95/hofor-scraper-{arch}
